name       : libmpdclient
version    : '2.13'
release    : 5
homepage   : http://www.musicpd.org/libs/libmpdclient/
source     :
    - http://www.musicpd.org/download/libmpdclient/2/libmpdclient-2.13.tar.xz : 5115bd52bc20a707c1ecc7587e6389c17305348e2132a66cf767c62fc55ed45d
license    : BSD-3-Clause
component  : multimedia.library
summary    : A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
description: |
    A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
