name       : libmpdclient
version    : '2.13'
release    : 6
homepage   : http://www.musicpd.org/libs/libmpdclient/
source     :
    - https://github.com/MusicPlayerDaemon/libmpdclient/archive/v2.13.tar.gz : e1583fbcae89ad543a6cc44caeaf16b31e709831f5b7eac4413f78c54a21db95
license    : BSD-3-Clause
component  : multimedia.library
summary    : A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
description: |
    A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
