name       : libmpdclient
version    : '2.19'
release    : 7
homepage   : https://www.musicpd.org/libs/libmpdclient/
source     :
    - https://github.com/MusicPlayerDaemon/libmpdclient/archive/refs/tags/v2.19.tar.gz : 12b566b75c3b6789ff8fc94698497d1f3fbaf0cbf9fa6c3a1e3906ef0d2bcbbb
license    : BSD-3-Clause
component  : multimedia.library
summary    : A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
description: |
    A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
