name       : libmpdclient
version    : 2.11
release    : 4
homepage   : http://www.musicpd.org/libs/libmpdclient/
source     :
    - http://www.musicpd.org/download/libmpdclient/2/libmpdclient-2.11.tar.xz : 15fe693893c0d7ea3f4c35c4016fbd0332836164178b20983eec9b470846baf6
license    : BSD-3-Clause
component  : multimedia.library
summary    : A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
description: |
    A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
setup      : |
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
