name       : libmpdclient
version    : 2.9
release    : 1
homepage   : http://www.musicpd.org/libs/libmpdclient/
source     :
    - http://www.musicpd.org/download/libmpdclient/2/libmpdclient-2.9.tar.xz : 7cc97ba560e91addafe5975f7e7da04b95d6710750e47b3367fa0d8c3b7699ca
license    : BSD-3-Clause
summary    : A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
description: |
   	A stable, documented, asynchronous API library for interfacing MPD in the C, C++ & Objective C languages.
setup      : |
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
